### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by Sayed-Afnan-Khazi** [gdsc-jssstu/HDU-University-Website#3]
Create an aesthetic landing page for HDU. You can refer to the [Figma vision](https://www.figma.com/proto/aILrEaqatJsdRCtWM5KgE6/Jssstu-web?node-id=15-97&starting-point-node-id=15%3A97) of this project for inspiration.

**Comment by priyanshu-gupta0503** [comment]
hey@Sayed-Afnan-khazi pls assign this is to me

**Comment by Sayed-Afnan-Khazi** [comment]
Hey @priyanshu-gupta0503 , sure, feel free to send a PR linked to this issue. Looking forward to seeing your PR

**Comment by priyanshu-gupta0503** [comment]
@Sayed-Afnan-Khazi  pls grant me this with a assign tag

**Comment by Sayed-Afnan-Khazi** [comment]
@priyanshu-gupta0503 I've assigned this issue to you, good luck!

**Comment by priyanshu-gupta0503** [comment]
hey@Sayed-Afnan-Khazi I have raised a pr kindly check it.

**Comment by priyanshu-gupta0503** [comment]
Kindly refer my
pr on creating a landing page.
After pr a code review and merge is blocked message is being shown.

**Comment by Sayed-Afnan-Khazi** [comment]
Hello @priyanshu-gupta0503, thanks for the PR. That message is normal. One of the maintainers will go through the changes soon and let you know if they merge it.

**Comment by Sayed-Afnan-Khazi** [comment]
Hey @priyanshu-gupta0503, could you please link your PR to this issue? You can do so by editing your PR comment and typing a keyword followed by this issue's number (3) with a #. You can refer to this [help link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
