### ISSUE TITLE
Create a responsive navigation bar

### ISSUE THREAD

**Issue by Sayed-Afnan-Khazi** [gdsc-jssstu/HDU-University-Website#4]
Create a responsive navigation bar for the HDU website. You can refer to the [Figma vision](https://www.figma.com/proto/aILrEaqatJsdRCtWM5KgE6/Jssstu-web?node-id=15-97&starting-point-node-id=15%3A97) of this project for the links required and for inspiration.

**Comment by Ramiz1336** [comment]
hi @Sayed-Afnan-Khazi I would like to work on this project, can you add a hacktoberfest2023 label to it?
 I have seen the figma vision and i believe i can make it.

**Comment by Sayed-Afnan-Khazi** [comment]
@Ramiz1336 The hacktoberfest label has been added to the repository. You can submit a PR and if it's merged, it should contribute to your Hacktoberfest PRs for 2023. Looking forward to your PR.

**Comment by Ramiz1336** [comment]
okkkh

**Comment by Sayed-Afnan-Khazi** [comment]
Good luck, @Ramiz1336 ! Looking forward to seeing your PR
