### ISSUE TITLE
Create an admissions page

### ISSUE THREAD

**Issue by Sayed-Afnan-Khazi** [gdsc-jssstu/HDU-University-Website#5]
Create an aesthetic admissions page for HDU.
You can also create an application form that can be submitted for enquiries.
You can refer to the [Figma vision](https://www.figma.com/proto/aILrEaqatJsdRCtWM5KgE6/Jssstu-web?node-id=15-97&starting-point-node-id=15%3A97) of this project for inspiration.

**Comment by Prithwi32** [comment]
@Sayed-Afnan-Khazi  may i know didn't the issue in not tagged hacktoberfest?

**Comment by Prithwi32** [comment]
> The PR should be counted for hacktoberfest since the repository has the hacktoberfest tag, don't worry. 😄 @Prithwi32

Fine😅😊
