### ISSUE TITLE
Design the homepage for mobile screens

### ISSUE THREAD

**Issue by Sayed-Afnan-Khazi** [gdsc-jssstu/HDU-University-Website#9]
The homepage for HDU looks great and is responsive for most screens, but an unconventional ordering of information and long scrolling can confuse visitors. We need to design a better homepage view for mobile screens.

For this issue, we're looking for graphic designers to reimagine the HDU homepage for mobile screens. You can contribute your designs as a link to a Figma file in the GRAPHIC_DESIGNS.md file under [Contributed Graphic Designs](https://github.com/gdsc-jssstu/HDU-University-Website/blob/main/GRAPHIC_DESIGNS.md#contributed-graphic-designs), or add an image under the same heading directly.

**Comment by nida242004** [comment]
I'd like to contribute to this issue, could you please assign it to me? @Sayed-Afnan-Khazi

**Comment by Sayed-Afnan-Khazi** [comment]
Sure, I've assigned this issue to you. Good luck, looking forward to see your PR!
